// This is a script to build, test and release mxnet docker images.
// This runs as a separate job and 
try {
     stage('Checkout'){
        node("Docker_Host_Ubuntu") {
            checkout scm
        }
     }

     stage('Build Docker'){
        node("Docker_Host_Ubuntu") {
            sh 'cd docker && chmod 777 run.sh && ./run.sh'
        }
     }
     } catch (err) {
        currentBuild.result = "FAILURE"
        mail body: "project build error is here: ${env.BUILD_URL}" ,
        from: 'mxnet-ci@amazon.com',
        replyTo: 'mxnet-ci@amazon.com',
        subject: 'project build failed',
        to: 'mbaijal@amazon.com'

        throw err
    }

